Project/Project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("social.urls")),
    path('admin/', admin.site.urls),
]

Project/social/urls.py
from django.urls import path
from .views import base, profilelist, profile

app_name = "social"

urlpatterns = [
    path("", base, name="base"),
    path("profilelist/", profilelist, name="profilelist"),
    path("profile/<int:pk>", profile, name="profile"),
]

Project/social/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    follows = models.ManyToManyField(
        "self",
        related_name="followed_by",
        symmetrical=False,
        blank=True
    )

    def __str__(self):
        return self.user.username

@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        user_profile = Profile(user=instance)
        user_profile.save()
        user_profile.follows.set([instance.profile.id])
        user_profile.save()

class Post(models.Model):
    user = models.ForeignKey(
        User, related_name="posts", on_delete=models.DO_NOTHING
    )
    body = models.CharField(max_length=140)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return (
            f"{self.user} "
            f"({self.created_at:%Y-%m-%d %H:%M}): "
            f"{self.body[:30]}..."
        )

Project/social/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    body = forms.CharField(
        required=True,
        widget=forms.widgets.Textarea(
            attrs={
                "placeholder": "Post something...",
                "class": "textarea is-success is-medium",
            }
        ),
        label="",)

    class Meta:
        model = Post
        exclude = ("user", )

Project/social/views.py
from multiprocessing import context
from .forms import PostForm
from django.shortcuts import render
from .models import Post, Profile
from django.shortcuts import render, redirect

def base(request):
    if request.method == "POST":
        form = PostForm(request.POST or None)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect("social:base")
    followed_posts = Post.objects.filter(
        user__profile__in=request.user.profile.follows.all()
    ).order_by("-created_at")
            
    form = PostForm()
    context = {"form": form,
    "posts": followed_posts}
    return render(request, "dashboard.html", context)
    

def profilelist(request):
    profiles = Profile.objects.exclude(user=request.user)
    context = {"profiles": profiles}
    return render(request, "profilelist.html", context)

def profile(request, pk):
    if not hasattr(request.user, 'profile'):
        missing_profile = Profile(user=request.user)
        missing_profile.save()
        
    profile = Profile.objects.get(pk=pk)
    if request.method == "POST":
        current_user_profile = request.user.profile
        data = request.POST
        action = data.get("follow")
        if action == "follow":
            current_user_profile.follows.add(profile)
        elif action == "unfollow":
            current_user_profile.follows.remove(profile)
        current_user_profile.save()
    context = {"profile": profile}
    return render(request, "profile.html", context)

Project/social/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Include the Bulma CSS framework for styling -->
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <title>Dwitter</title>
</head>
<body>
    <a href="{% url 'social:base' %} ">
    <section class="hero is-small is-danger mb-4">
        <div class="hero-body">
            <h1 class="title is-1">SocialNetwork</h1>
            <p class="subtitle is-4">
                Social network built with Django
            </p>
        </div>
    </section>
</a>

    <div class="container">
        <div class="columns">

            {% block content %}

            {% endblock content %}

        </div>
    </div>
</body>
</html>

Project/social/templates/dashboard.html
{% extends 'base.html' %}

{% block content %}

<div class="column">
    {% for post in posts %}
    <div class="box">
        {{post.body}}
        <span class="is-small has-text-grey-light">
            ({{ post.created_at }} by {{ post.user.username }}
        </span>
    </div>
{% endfor %}
</div>
<div class="column is-one-third">
    <div class="block">
        <a href="{% url 'social:profilelist' %} ">
            <button class="button is-dark is-outlined is-fullwidth">
                All Profiles
            </button>
        </a>
    </div>
    <div class="block">
        <a href="{% url 'social:profile' request.user.profile.id %} ">
            <button class="button is-success is-light is-outlined is-fullwidth">
                My Profile
            </button>
        </a>
    </div>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="button is-success is-fullwidth is-medium mt-5"
                type="submit">Post
        </button>
    </form>
</div>

{% endblock content %}}

Project/social/templates/profile.html
{% extends 'base.html' %}

{% block content %}

<div class="column">

    <div class="block">
    <h1 class="title is-1">
        {{profile.user.username|upper}}'s Dweets
    </h1>
    </div>
    <form method="post">
        {% csrf_token %}
        <div class="buttons has-addons">
            {% if profile in user.profile.follows.all %}
                <button class="button is-success is-static">Follow</button>
                <button class="button is-danger" name="follow" value="unfollow">Unfollow</button>
            {% else %}
            <button class="button is-success" name="follow" value="follow">Follow</button>
                <button class="button is-danger is-static">Unfollow</button>
            {% endif %}
        </div>
    </form>
    <div class="content">
        {% for post in profile.user.posts.all %}
            <div class="box">
                {{ post.body }}
                <span class="is-small has-text-grey-light">
                    ({{ post.created_at }})
                </span>
            </div>
        {% endfor %}
    </div>
</div>

<div class="column is-one-third">

    <div class="block">
        <a href="{% url 'social:profilelist' %}">
            <button class="button is-dark is-outlined is-fullwidth">
                All Profiles
            </button>
        </a>
    </div>

    <div class="block">
        <h3 class="title is-4">
            {{profile.user.username}} follows:
        </h3>
        <div class="content">
            <ul>
            {% for following in profile.follows.all %}
                <li>
                    <a href="#">
                        {{ following }}
                    </a>
                </li>
            {% endfor %}
            </ul>
        </div>
    </div>

    <div class="block">
        <h3 class="title is-4">
            {{profile.user.username}} is followed by:
        </h3>
        <div class="content">
            <ul>
            {% for follower in profile.followed_by.all %}
                <li>
                    <a href="#">
                        {{ follower }}
                    </a>
                </li>
            {% endfor %}
            </ul>
        </div>
    </div>

</div>

{% endblock content %}

Project/social/templates/profilelist.html
{% extends 'base.html' %}

{% block content %}

<div class="column">

{% for profile in profiles %}

    <div class="block">
      <div class="card">
        <a href="{% url 'social:profile' profile.id %}">
          <div class="card-content">
            <div class="media">
              <div class="media-left">
                <figure class="image is-48x48">
                  <img src="https://bulma.io/images/placeholders/96x96.png"
                       alt="Placeholder image">
                </figure>
              </div>
              <div class="media-content">
                <p class="title is-4">
                  {{ profile.user.username }}
                </p>
                <p class="subtitle is-6">
                  @{{ profile.user.username|lower }}
                </p>
              </div>
            </div>
          </div>
        </a>
      </div>
    </div>

{% endfor %}

</div>

{% endblock content %}